Optimizations + code changes
Terasology/Lakes pull request #2
Opened 2019-06-29 15:37 UTC by Adrijaned

2019-11-03 22:25 UTC, skaldarnar approved these changes
Thanks for the changes, code looks a bit cleaner and we can always make use of better documentation! I've slightly changed some of the doc comments and will merge it now 😃

2019-11-03 22:25 UTC, skaldarnar commented on src/main/java/org/terasology/Lakes/Lake.java
> +     * Returns the y position of the surface od the lake.
```suggestion
     * Returns the y position of the lake surface.
```

2019-11-03 22:25 UTC, skaldarnar commented on src/main/java/org/terasology/Lakes/LakeDepthFacet.java
> + * Marks how deep a lake would be were there some in a particular world xz coordinates.
Does this facet provide the depth in absolute values or as difference to the "real" surface height?

If I read `LakeDepthProvider` correctly this facet returns a positive floating point value denoting the depth of the lake at a given position:

```suggestion
 * Marks how deep a lake would be at given world coordinates (x, z).
 *
 * The lake depth is given as positive floating point value which should be interpreted as depth from actual surface height.
```

2019-11-03 22:29 UTC, skaldarnar requested changes
@Adrijaned actually, I cannot apply the suggestions myself due to missing permissions (🤔 probably because that would mean to push to a branch on your fork...). 
Please be so kind to apply the suggestions (can do that via GitHub web interface) and ping me again 🙃

2019-11-04 16:41 UTC, Adrijaned commented
@skaldarnar

2019-11-04 22:07 UTC, skaldarnar approved these changes
Thanks a lot!

2019-11-04 22:07 UTC, merged